definitions:
  model.Item:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      item_code:
        type: string
      order_uuid:
        type: string
      quantity:
        type: integer
      updated_at:
        type: string
    type: object
  model.ItemDTO:
    properties:
      description:
        type: string
      item_code:
        type: string
      quantity:
        type: integer
    type: object
  model.OrderHandler.request:
    properties:
      customer_name:
        type: string
      items:
        items:
          $ref: '#/definitions/model.ItemDTO'
        type: array
      ordered_at:
        type: string
    type: object
  model.OrderHandler.response:
    properties:
      customer_name:
        type: string
      items:
        items:
          $ref: '#/definitions/model.Item'
        type: array
      ordered_at:
        type: string
      uuid:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8082
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /order:
    post:
      consumes:
      - application/json
      description: Create Order
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.OrderHandler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OrderHandler.response'
      summary: Create Order
      tags:
      - order
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
